#!/usr/bin/env python3
"""Install a site-bound Snakemake profile for one-command workflow starts."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml


PIPELINE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PIPELINE_ROOT))

from site_config import configure  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create ~/.config/snakemake/NAME/config.yaml from an execution "
            "profile and an installed site configuration."
        )
    )
    parser.add_argument("--site-config", required=True, type=Path)
    parser.add_argument("--profile-name", default="zslurm2")
    parser.add_argument(
        "--profile-template",
        type=Path,
        default=PIPELINE_ROOT / "profiles" / "spider" / "config.yaml",
        help="base execution profile (default: profiles/spider/config.yaml)",
    )
    parser.add_argument(
        "--destination",
        type=Path,
        help="profile directory (default: ~/.config/snakemake/PROFILE_NAME)",
    )
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.profile_name or any(
        separator in args.profile_name for separator in ("/", "\\")
    ):
        raise SystemExit("--profile-name must be one directory name")

    site_config = args.site_config.expanduser().resolve(strict=True)
    settings = configure({"site_config": str(site_config)})

    template = args.profile_template.expanduser().resolve(strict=True)
    profile = yaml.safe_load(template.read_text(encoding="utf-8"))
    if not isinstance(profile, dict):
        raise SystemExit(f"Invalid profile template: {template}")

    profile["snakefile"] = str(PIPELINE_ROOT / "Snakefile")
    profile["conda-prefix"] = settings.values["conda_prefix"]
    profile["apptainer-prefix"] = settings.values["apptainer_prefix"]
    profile["rerun-triggers"] = "mtime"
    profile["config"] = [f"site_config={site_config}"]

    default_destination = Path.home() / ".config" / "snakemake" / args.profile_name
    destination = args.destination.expanduser() if args.destination else default_destination
    destination = destination.resolve()
    output = destination / "config.yaml"
    if output.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite {output}; pass --force to replace it")

    destination.mkdir(parents=True, exist_ok=True)
    temporary = destination / ".config.yaml.tmp"
    temporary.write_text(
        "# Generated by scripts/install_site_profile.py.\n"
        + yaml.safe_dump(profile, sort_keys=False),
        encoding="utf-8",
    )
    temporary.replace(output)

    print(f"Installed Snakemake profile: {output}")
    profile_argument = (
        args.profile_name
        if destination == default_destination.resolve()
        else str(destination)
    )
    print(
        "Start a cohort with: "
        f"snakemake --profile {profile_argument} "
        "--zslurm-instance INSTANCE"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
