schema_version: 1
site: snellius

paths:
  resource_root: /gpfs/work3/0/qtholstg/hg38_res_v2
  software_root: /gpfs/work3/0/qtholstg/hg38_res_v2/software
  shared_tmp_root: tmp
  fallback_tmp_root: /scratch-local
  conda_prefix: /home/hulsmanm/.snakemake
  apptainer_prefix: /home/hulsmanm/.apptainer
  deepvariant_native_prefix: /gpfs/work3/0/qtholstg/hg38_res_v2/software/deepvariant-1.9.0-native
  hg19_reference: /gpfs/work3/0/qtholstg/hg38_res_v2/cram_refs/hg19.fa
  hg19_b37_chry_reference: /gpfs/work3/0/qtholstg/marc/genome/hg19_b37chrY.fa
  hg38_cram_reference: /gpfs/work3/0/qtholstg/hg38_res_v2/cram_refs/GRCh38_full_analysis_set_plus_decoy_hla.fa
  glnexus_preset: /gpfs/work3/0/qtholstg/hg38_res_v2/software/Glnexus_preset.yml
  check_empty_script: /gpfs/work3/0/qtholstg/hg38_res_v2/scripts/check_empty.py

storage:
  dcache_processed_config: /gpfs/work3/0/qtholstg/hg38_res_v2/.agh/agh_processed.conf
  dcache_read_config: /gpfs/work3/0/qtholstg/hg38_res_v2/.agh/agh_processed.conf
  dcache_read_prefix: agh_full_snellius:/tape/processed

tools:
  ada: /gpfs/work3/0/qtholstg/hg38_res_v2/software/SpiderScripts/ada/ada
  dcache_cp: dcache_cp
  rclone: rclone
  daget: /opt/dacommands/bin/daget
  dals: /opt/dacommands/bin/dals
  darelease: /opt/dacommands/bin/darelease

encryption:
  sender_private_key: /gpfs/work3/0/qtholstg/hg38_res_v2/.c4gh/master_key_for_encryption
  recipient_public_keys:
    - /gpfs/work3/0/qtholstg/hg38_res_v2/.c4gh/recipient1.pub
    - /gpfs/work3/0/qtholstg/hg38_res_v2/.c4gh/recipient2.pub
  decryption_private_key: /gpfs/work3/0/qtholstg/hg38_res_v2/.c4gh/recipient1
  decryption_passphrase_file: ""
