schema_version: 1
site: spider

paths:
  resource_root: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2
  software_root: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/software
  shared_tmp_root: /project/holstegelab/Data/short_read_pipeline/tmp
  fallback_tmp_root: /project/holstegelab/Data/short_read_pipeline/tmp
  conda_prefix: /project/holstegelab/Software/short_read_pipeline/conda
  apptainer_prefix: /project/holstegelab/Software/short_read_pipeline/apptainer
  deepvariant_native_prefix: /project/holstegelab/Software/short_read_pipeline/deepvariant-1.9.0-native
  hg19_reference: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/cram_refs/hg19.fa
  hg19_b37_chry_reference: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/cram_refs/hg19_b37chrY.fa
  hg38_cram_reference: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/cram_refs/GRCh38_full_analysis_set_plus_decoy_hla.fa
  glnexus_preset: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/software/Glnexus_preset.yml
  check_empty_script: /project/holstegelab/Software/short_read_pipeline/hg38_res_v2/scripts/check_empty.py

storage:
  dcache_processed_config: ${HOME}/.config/short-read-pipeline/processed.conf
  dcache_read_config: ${HOME}/.config/short-read-pipeline/read.conf
  dcache_read_prefix: hg38_res_v2_20260914_spider:/

tools:
  ada: ada
  dcache_cp: dcache_cp
  rclone: rclone
  daget: daget
  dals: dals
  darelease: darelease

encryption:
  sender_private_key: ${HOME}/.config/short-read-pipeline/c4gh/master_key_for_encryption
  recipient_public_keys:
    - ${HOME}/.config/short-read-pipeline/c4gh/recipient1.pub
    - ${HOME}/.config/short-read-pipeline/c4gh/recipient2.pub
  decryption_private_key: ${HOME}/.config/short-read-pipeline/c4gh/recipient1
  decryption_passphrase_file: ""
